---
title: "DATA"
author: "Wenyu Zhang and Weize Sun"
output: 
  html_document:
    toc: true
    toc_float: true
---

## Data source

The data was collected from NYC open data, which is about NYPD Complaint Data Historic. This dataset includes all valid felony, misdemeanor, and violation crimes reported to the New York City Police Department (NYPD) from 2006 to the end of last year (2020). The data was collected annually. The dataset has 7.38M rows and 35 variables; each row is a complaint.

Feel free to check the data in [NYC OpenData](https://data.cityofnewyork.us/Public-Safety/NYPD-Complaint-Data-Historic/qgea-i56i)



## Data cleaning

The data was first imported into R. This is a huge dataset which contains about 7.5 million rows, so we have to do some data cleaning before doing data analysis. After reading the data, we deleted some columns (variables) which include too many blank spaces, since we thought they were not helpful for our data analysis. Then, for the convenience of further data analysis, we divided the variable `cmplnt_fr_dt` (the exact date of occurrence for the reported case) into three variables: `year`, `month`, and `day`. Since this dataset is too large for a normal personal computer to run, we divided it into more than a dozen small datasets by year to speed up data processing. Our current data analysis is mostly based on 2020’s dataset, because it’s the latest year's data.


## Variables of interest
While cleaning data, we mutated the original variables to variables which could be easily understood. Below are the mutated key variables.

`month`

`day`

`exact_crime_time`: the exact time of occurrence for the reported crime.

`description_of_crime`

`level_of_offence`: felony, misdemeanor, or violation.

`name_of_borough`: Bronx, Brooklyn, Manhattan, Queens, and Staten Island.

`susp_age_group`: suspect’s age group.

`susp_race`: suspect’s race.

`susp_sex`: suspect’s gender.

`vic_age_group`: victim’s age group.

`vic_race`: victim’s race.

`vic_sex`: victim’s gender.



