---
title: "Time Line"
author: "Yiming Li"
output: 
 html_document:
    toc: true
    toc_float: true
---

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r, echo = FALSE, message=FALSE,warning = FALSE}
filename = list.files(path = "../data2") 
pathname = str_c("../data2/", filename)
```


```{r, echo = FALSE, message=FALSE,warning = FALSE}
time_count_df = 
  tibble(
  filename,
  data = purrr::map(.x = pathname, ~read_csv(.x)) 
) %>% 
  unnest(cols = data) 
```

```{r, echo = FALSE, message=FALSE,warning = FALSE}
time_count_df_2016 = 
  time_count_df %>% 
  filter(date >= "2016-01-01")
```

## 2016 - 2020 daily count
```{r}
time_count_df_2016 %>% 
  ggplot(aes(x = date, y = count, color = name_of_borough)) +
  geom_point(alpha = 0.05) +
  geom_smooth(se = FALSE)
```



